# Default values for deckard.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: blipai/deckard
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

labels: {}

# To control deckard's housekeeping
housekeeper:
  # If the housekeeper task will run in a separate deployment
  enabled: true

  image:
    repository: blipai/deckard
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  # The number of replicas for the housekeeper deployment
  replicaCount: 1

  # If the housekeeper task will run in the same pod as the deckard gRPC service
  # Useful for development purposes when you don't want a separate deployment for the housekeeper
  self:
    enabled: false

# To control Deckard's audit system
audit:
  # Deckard's DECKARD_AUDIT_ENABLED environment variable
  enabled: false

env: []

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

storage:
  # Deckard's DECKARD_STORAGE_TYPE environment variable
  # Available options: MONGODB, MEMORY
  # Remember to set the mongodb.enabled to false if you want to use a self-deployed MongoDB or a Memory storage
  type: MONGODB
  # Deckard's DECKARD_STORAGE_URI environment variable.
  # By default this chart will use the deployed MongoDB's URI
  # If you change MongoDB architecture to replicaSet you must set the URI to the replicaSet URI
  # TODO: deal with non standalone MongoDB deployments to generate the URI dinamically in the deployment.yaml
  uri: ""
  mongodb:
    # Deckard's DECKARD_MONGODB_DATABASE environment variable
    database: "deckard"
    # Deckard's DECKARD_MONGODB_COLLECTION environment variable
    collection: "queue"
    # Deckard's DECKARD_MONGODB_QUEUE_CONFIGURATION_COLLECTION environment variable
    queue_configuration_collection: "queue_configuration"

# See available options here: https://github.com/bitnami/charts/tree/main/bitnami/mongodb
mongodb:
  enabled: true
  auth:
    enabled: true
    # In a production environment prefer setting all passwords and configurations using mongodb's existingSecret chart field
    rootUser: deckard
    rootPassword: deckard
  architecture: standalone

cache:
  # Deckard's DECKARD_REDIS_TYPE environment variable
  # Available options: REDIS, MEMORY
  # Remember to set the redis.enabled to false if you want to use a self-deployed Redis or a Memory storage
  type: REDIS
  # Deckard's DECKARD_CACHE_URI environment variable.
  # By default this chart will use the deployed Redis's URI
  # If you change Redis architecture you must set the URI by yourself
  # TODO: deal with non standalone Redis deployments to generate the URI dinamically in the deployment.yaml
  uri: ""
  redis:
    # Deckard's DECKARD_REDIS_DB environment variable
    database: 0

# See available options here: https://github.com/bitnami/charts/tree/main/bitnami/redis
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: deckard


service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false
  className: ""
  annotations: {}
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
