{{- $storageURI := include "deckard.storage.uri" . -}}
{{- $cacheURI := include "deckard.cache.uri" . -}}
{{- if eq (include "deckard.shouldCreateStorageConnectionSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deckard.storageConnectionSecretName" . }}
  labels:
    {{- include "deckard.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.connectionSecret.storage.key }}: {{ $storageURI | quote }}
{{- end }}
{{- if and (eq (include "deckard.shouldCreateStorageConnectionSecret" .) "true") (eq (include "deckard.shouldCreateCacheConnectionSecret" .) "true") }}
---
{{- end }}
{{- if eq (include "deckard.shouldCreateCacheConnectionSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deckard.cacheConnectionSecretName" . }}
  labels:
    {{- include "deckard.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.connectionSecret.cache.key }}: {{ $cacheURI | quote }}
{{- end }}