apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deckard.fullname" . }}
  labels:
    {{- include "deckard.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "deckard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "deckard.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $name, $item := .Values.env }}
            - name: {{ $name }}
              {{- $item | toYaml | nindent 14 }}
            {{- end }}
            - name: DECKARD_METRICS_ENABLED
              value: {{ quote .Values.metrics.enabled }}
            - name: DECKARD_METRICS_PORT
              value: {{ quote .Values.metrics.port }}
            - name: DECKARD_METRICS_PATH
              value: {{ quote .Values.metrics.path }}
            - name: DECKARD_GRPC_PORT
              value: {{ quote .Values.service.port }}
            - name: DECKARD_CACHE_TYPE
              value: {{ .Values.cache.type }}
            - name: DECKARD_STORAGE_TYPE
              value: {{ .Values.storage.type }}
            - name: DECKARD_AUDIT_ENABLED
              value: {{ quote .Values.audit.enabled }}
            - name: DECKARD_HOUSEKEEPER_ENABLED
              value: {{ quote .Values.housekeeper.self.enabled }}
            - name: DECKARD_STORAGE_URI
              value: {{ include "deckard.storage.uri" . | quote }}
            - name: DECKARD_CACHE_URI
              value: {{ include "deckard.cache.uri" . | quote }}
            - name: DECKARD_REDIS_DB
              value: {{ quote .Values.cache.redis.database }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.containerPorts }}
            {{- range $name, $item := .Values.containerPorts }}
            - name: {{ $name }}
              {{- $item | toYaml | nindent 14 }}
            {{- end }}
            {{- end }}
          livenessProbe:
            grpc:
              port: {{ .Values.service.port }}
          readinessProbe:
            grpc:
              port: {{ .Values.service.port }}
          startupProbe:
            grpc:
              port: {{ .Values.service.port }}
            failureThreshold: 30
            periodSeconds: 2
            initialDelaySeconds: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
