{
 "title": "Deckard Status",
 "tags": [
  "deckard",
  "social-metrics-updater"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "res",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "queue",
    "label": "queue",
    "query": {
     "query": "label_values(deckard_total_messages, queue)"
    }
   },
   {
    "name": "service_name",
    "label": "service_name",
    "query": {
     "query": "query_result(deckard_cache_latency_count)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Storage / Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Storage Accesses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(deckard_storage_latency_count{retry!=\"true\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (op)",
       "legendFormat": "{{op}}"
      },
      {
       "expr": "sum(increase(deckard_storage_latency_count{retry=\"true\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (op)",
       "legendFormat": "{{op}} (retry)"
      }
     ]
    },
    {
     "title": "Cache Accessess",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(deckard_cache_latency_bucket{app_kubernetes_io_name=~\"$service_name\"}[$res])) by (op)",
       "legendFormat": "{{op}}"
      }
     ]
    },
    {
     "title": "Storage latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deckard_storage_latency_bucket{retry!=\"true\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (le, op))",
       "legendFormat": "{{op}}  p99"
      },
      {
       "expr": "histogram_quantile(.99, sum(rate(deckard_storage_latency_bucket{retry=\"true\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (le, op))",
       "legendFormat": "{{op}} (retry) p99"
      }
     ]
    },
    {
     "title": "Cache latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(deckard_cache_latency_bucket{app_kubernetes_io_name=~\"$service_name\"}[$res])) by (le, op))",
       "legendFormat": "{{op}} p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oldest Message by Queue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(deckard_oldest_message{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Total Elements by Queue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(deckard_total_messages{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "ACKs by Queue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deckard_ack{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum(increase(deckard_ack_total{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Timeouts by Queue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deckard_message_timeout{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum(increase(deckard_message_timeout_total{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Empty Queue Pull",
   "type": "graph",
   "description": "Number of times a pull is made against an empty queue.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deckard_messages_empty_queue_not_found_storage_total{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
     "legendFormat": "{{queue}} missing-storage"
    },
    {
     "expr": "sum(increase(deckard_messages_empty_queue_total{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
     "legendFormat": "{{queue}} empty-queue"
    },
    {
     "expr": "sum(increase(deckard_messages_empty_queue_not_found_storage{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
     "legendFormat": "{{queue}} missing-storage"
    },
    {
     "expr": "sum(increase(deckard_messages_empty_queue{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
     "legendFormat": "{{queue}} empty-queue"
    }
   ]
  },
  {
   "title": "Missing Storage Elements",
   "type": "graph",
   "description": "Number of elements from cache that were not found in the storage",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deckard_messages_not_found_in_storage_total{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
     "legendFormat": "{{queue}}"
    },
    {
     "expr": "sum(increase(deckard_messages_not_found_in_storage{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Cleaner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TTL",
     "type": "graph",
     "description": "Number of elements removed by exceeding TTL",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(deckard_ttl_messages_removed_total{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
       "legendFormat": "storage - {{queue}}"
      },
      {
       "expr": "sum(increase(deckard_ttl_messages_cache_removed_total{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
       "legendFormat": "cache - {{queue}}"
      },
      {
       "expr": "sum(increase(deckard_ttl_messages_removed{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
       "legendFormat": "storage - {{queue}}"
      },
      {
       "expr": "sum(increase(deckard_ttl_messages_cache_removed{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
       "legendFormat": "cache - {{queue}}"
      }
     ]
    },
    {
     "title": "Max elements",
     "type": "graph",
     "description": "Number of elements removed by exceeding queue max elements",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(deckard_exceeding_messages_removed_total{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
       "legendFormat": "storage - {{queue}}"
      },
      {
       "expr": "sum(increase(deckard_exceeding_messages_cache_removed_total{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
       "legendFormat": "cache - {{queue}}"
      },
      {
       "expr": "sum(increase(deckard_exceeding_messages_removed{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
       "legendFormat": "storage - {{queue}}"
      },
      {
       "expr": "sum(increase(deckard_exceeding_messages_cache_removed{queue=~\"$queue\", app_kubernetes_io_name=~\"$service_name\"}[$res])) by (queue)",
       "legendFormat": "cache - {{queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage per container (gRPC)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_requests{container=~\"deckard|deckard-listening\", resource=\"cpu\"}) by (container)",
       "legendFormat": "{{container}} request"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{container=~\"deckard|deckard-listening\", resource=\"cpu\"}) by (container)",
       "legendFormat": "{{container}} limit"
      },
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{container=~\"deckard|deckard-listening\",pod!=\"\"}[5m])) by (pod)",
       "legendFormat": "{{pod}} usage"
      }
     ]
    },
    {
     "title": "CPU Usage per container (Housekeeper)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_requests{container=~\"deckard-housekeeper|deckard-listening-housekeeper\", resource=\"cpu\"}) by (container)",
       "legendFormat": "{{container}} request"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{container=~\"deckard-housekeeper|deckard-listening-housekeeper\", resource=\"cpu\"}) by (container)",
       "legendFormat": "{{container}} limit"
      },
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{container=~\"deckard-housekeeper|deckard-listening-housekeeper\",pod!=\"\"}[5m])) by (pod)",
       "legendFormat": "{{pod}} usage"
      }
     ]
    },
    {
     "title": "Memory usage per container (gRPC)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_requests{container=~\"deckard|deckard-listening\",resource=\"memory\"}) by (container)",
       "legendFormat": "{{container}} request"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{container=~\"deckard|deckard-listening\",resource=\"memory\"}) by (container)",
       "legendFormat": "{{container}} limit"
      },
      {
       "expr": "max(container_memory_working_set_bytes{container=~\"deckard|deckard-listening\",container!=\"\"}) by (pod)",
       "legendFormat": "{{pod}} usage"
      }
     ]
    },
    {
     "title": "Memory usage per container (Housekeeper)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_requests{container=~\"deckard-housekeeper|deckard-listening-housekeeper\",resource=\"memory\"}) by (container)",
       "legendFormat": "{{container}} request"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{container=~\"deckard-housekeeper|deckard-listening-housekeeper\",resource=\"memory\"}) by (container)",
       "legendFormat": "{{container}} limit"
      },
      {
       "expr": "max(container_memory_working_set_bytes{container=~\"deckard-housekeeper|deckard-listening-housekeeper\",container!=\"\"}) by (pod)",
       "legendFormat": "{{pod}} usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Code Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Code Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(deckard_code_usage_total{app_kubernetes_io_name=~\"$service_name\"}[$res])) by (type)",
       "legendFormat": "{{queue}}"
      }
     ]
    }
   ]
  }
 ]
}