name: Deploy Deckard Helm chart to Github Pages

on:
  release:
    types:
      - released

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Setup Helm
        uses: azure/setup-helm@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build chart dependencies
        working-directory: helm
        run: helm dependency update .
      - name: Lint chart
        working-directory: helm
        run: helm lint .
      - name: Package chart
        working-directory: helm
        run: helm package .
      - name: Prepare release directory
        run: |
          mkdir -p helm-release
          cp helm/deckard-*.tgz helm-release/
          helm repo index helm-release --url https://takenet.github.io/deckard/
          touch helm-release/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'helm-release/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5