name: Lint

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

env:
  GO_VERSION: 1.18

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v3

      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@latest

      - name: Make gen-mocks
        run: make gen-mocks
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true